// Every numeric threshold used by rules and indices lives here (PRD
// Appendix A). Changing a number here must not require touching rule logic.

export const T = Object.freeze({
  rain: {
    umbrellaProb: 60,
    umbrellaMm: 0.5,
    umbrellaSevereProb: 80,
    umbrellaSevereMm: 4,
    heavy3hMm: 15.6,
    ridingMmPerHour: 7.6,
    dayHeavyMm: 64.5,
    schoolProb: 40,
    noSprayProb: 50,
    noSprayHours: 6,
    eventProb: 50,
  },
  heat: { tipHi: 41, severeHi: 54, warmNightMin: 30, workDangerHi: 41, schoolHi: 38 },
  cold: { plainsMin: 10, severeMin: 4 },
  fog: { tipVisibilityM: 500, dense: 200, veryDense: 50, flightVisibilityM: 800 },
  wind: { cautionGust: 25, strongGustEvents: 40, strongGustSea: 45, cyclingHeadwind: 25 },
  thunder: { probNext3h: 40, farmProb: 40, wmoCodes: [95, 96, 99], hailCodes: [96, 99] },
  dust: { pm10: 250, gust: 35 },
  aqi: { poor: 201, veryPoor: 301, severe: 401, sensitive: 101 },
  uv: { tip: 8, severe: 11 },
  humidity: { sensitive: 85, sensitiveHours: 3 },
  frost: { high: 2, moderate: 4, clearSkyCloud: 30, calmWind: 8 },
  soil: { dryTopsoil: 0.15, recentRainMm: 5, recentRainDays: 3 },
  sea: {
    stayOutWave: 2.0,
    cautionWave: 1.0,
    longSwellHeight: 1.5,
    longSwellPeriod: 12,
    cautionPeriod: 10,
    stayOutGust: 45,
    cautionWind: 25,
    fisherWind: 45,
    fisherWave: 2.5,
    fisherCalmWind: 15,
    fisherCalmWave: 1.0,
  },
  spray: { windMin: 3, windMax: 10, noRainHours: 6, rainProbMax: 30, tempMax: 32, rhMin: 40 },
  lightning: { radiusKm: 10, waitMinutes: 30 },
  reports: { radiusKm: 0.5, maxAgeHours: 3, coolSpotKm: 2 },
  travel: { fogHorizonHours: 48, packHorizonDays: 7, hillElevationM: 1000 },
  events: { forecastHorizonDays: 16 },
  cards: { maxTipsPerMember: 6, visibleOnHome: 3 },
  goodEveningComfort: 75,
  windowMinScore: 50,
});
