// Build a Font Awesome subset (PRD 13.8 performance budget).
//
// The full Font Awesome stylesheet is ~69 KB (22 KB gzipped) of
// render-blocking CSS for thousands of icons, and its solid font is 156 KB.
// This script keeps only the icons the source uses:
//   - src/styles/icons.css: base rules + used icon rules + @font-face
//   - public/fonts/*.woff2: fonts subset to the used glyphs (needs Python
//     fontTools: `pip install fonttools brotli`); falls back to full fonts.
//
// Run after adding an icon: `node scripts/build-icons.mjs`.
// Icons must appear as literal class names (e.g. 'fa-cloud-sun') somewhere
// in src/, never assembled from pieces, or they will be missing.

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FA = join(ROOT, 'node_modules/@fortawesome/fontawesome-free');
const css = readFileSync(join(FA, 'css/all.min.css'), 'utf8');

function walk(dir, out = []) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(js|jsx|mjs)$/.test(f)) out.push(p);
  }
  return out;
}

const used = new Set();
for (const f of walk(join(ROOT, 'src'))) {
  for (const m of readFileSync(f, 'utf8').matchAll(/\bfa-[a-z0-9]+(?:-[a-z0-9]+)*/g)) used.add(m[0]);
}

// Base: everything before the first icon rule (layout, sizing, animation),
// plus the non-icon rules after the icon list (family variables and the
// .fa-solid / .fa-regular / .fa-brands weights). Font faces are rebuilt.
const firstIcon = css.indexOf('.fa-0{');
const head = css.slice(css.indexOf('*/') + 2, firstIcon).trim();
const isIconRule = (sel, body) => /^--fa:"\\/.test(body) && sel.split(',').every((x) => x.startsWith('.fa-'));
const tail = [];
for (const m of css.slice(firstIcon).matchAll(/([^{}@]+)\{([^{}]*)\}/g)) {
  const sel = m[1].trim();
  if (!sel || isIconRule(sel, m[2])) continue;
  tail.push(`${sel}{${m[2]}}`);
}
// @font-face bodies match the pattern without a selector (the "@" is
// excluded), so they arrive as "font-..." fragments and are dropped here.
const base = `${head}\n${tail.filter((r) => !r.startsWith('font-')).join('')}`;

// Icon rules look like `.fa-house{--fa:"\f015"}`, sometimes with aliases
// (`.fa-home,.fa-house{...}`).
const rules = [];
const codepoints = new Set();
for (const m of css.slice(firstIcon).matchAll(/((?:\.fa-[a-z0-9-]+,?)+)\{--fa:"\\([0-9a-f]+)"\}/g)) {
  const names = m[1].split(',').map((s) => s.slice(1)).filter(Boolean);
  const keep = names.filter((n) => used.has(n));
  if (!keep.length) continue;
  rules.push(`${keep.map((n) => `.${n}`).join(',')}{--fa:"\\${m[2]}"}`);
  codepoints.add(m[2]);
}

const styles = [
  ['fa-solid-900', 'Font Awesome 6 Free', 900, true],
  ['fa-regular-400', 'Font Awesome 6 Free', 400, used.has('fa-regular') || used.has('far')],
  ['fa-brands-400', 'Font Awesome 6 Brands', 400, used.has('fa-brands') || used.has('fab')],
].filter((s) => s[3]);

mkdirSync(join(ROOT, 'public/fonts'), { recursive: true });
let subset = true;
const unicodes = [...codepoints].map((c) => `U+${c}`).join(',');
for (const [file] of styles) {
  const src = join(FA, 'webfonts', `${file}.woff2`);
  const out = join(ROOT, 'public/fonts', `${file}.woff2`);
  try {
    execFileSync('python3', ['-m', 'fontTools.subset', src, `--unicodes=${unicodes}`, '--flavor=woff2', `--output-file=${out}`, '--layout-features=*'], {
      stdio: 'pipe',
      env: process.env,
    });
  } catch {
    subset = false;
    copyFileSync(src, out);
  }
}

const faces = styles
  .map(([file, family, weight]) => `@font-face{font-family:"${family}";font-style:normal;font-weight:${weight};font-display:block;src:url(/fonts/${file}.woff2) format("woff2")}`)
  .join('\n');

const header = `/* Generated by scripts/build-icons.mjs from Font Awesome Free ${JSON.parse(readFileSync(join(FA, 'package.json'), 'utf8')).version}.
   Do not edit; re-run the script after adding icons.
   Font Awesome Free: icons CC BY 4.0, fonts SIL OFL 1.1, code MIT (https://fontawesome.com/license/free). */`;
writeFileSync(join(ROOT, 'src/styles/icons.css'), `${header}\n${base}\n${rules.join('')}\n${faces}\n`);

console.log(`icons: ${rules.length} rules, ${codepoints.size} glyphs, fonts ${subset ? 'subset' : 'copied in full (fontTools not found)'}`);
